### ISSUE TITLE
See all requests

### ISSUE THREAD

**Issue by connie-reinholdsson** [AlexJukes/makersbnb#3]
As a landlord,
So that I can choose the guest,
I want to be able to see all the requests I've received.

**Comment by connie-reinholdsson** [comment]
As a landlord,
So that I can choose the guest,
I want to be able to see all the requests before I confirm.

**Comment by connie-reinholdsson** [comment]
As a landlord,
So that I can choose the guest,
I want to be able to see all the requests before I confirm.

**Comment by colinturner** [comment]
We need to create the Request class before addressing this issue. In Backlog until then.
